trigger:
  branches:
    include:
    - main
    - releases/*
  paths:
    include:
    - cgmml/commmon/zscore/*

pr: none

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip==20.2
    pip install numpy==1.19.1 glob2==0.7 wheel
  displayName: 'Install dependencies'

- script: |
    cd cgmml/common/zscore
    python setup.py sdist bdist_wheel
  displayName: 'Create Package'

- script: |
    cd cgmml/common/zscore
    pip install twine
    python -m twine upload --skip-existing --verbose -p $(PYPITOKEN1) -u __token__ --repository cgmzscore --repository-url https://upload.pypi.org/legacy/ dist/*.whl
  displayName: 'Upload package'
