# Inspired by https://github.com/airctic/icedata/blob/master/.github/workflows/pypi-release.yml
name: PyPi Release

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Setup dependencies
      run: python -m pip install --user --upgrade setuptools wheel

    - name: Build package
      run: python setup.py sdist bdist_wheel

    - name: Debug secret
      run: echo ${{ secrets.test_pypi_password }}

    - name: Publish package to TestPyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.test_pypi_password }}
        repository_url: https://test.pypi.org/legacy/
        verbose: true

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
        verbose: true
